### ISSUE TITLE
Server Fails To Start

### ISSUE THREAD

**Issue by Flute7** [TechUnRestricted/PSDirectSender#1]
I have followed setup instructions very closely, however 'Check Server Status' always returns a 'Failed' message. Server IP and Port are automatically generated.
I have verified successful connection to PS4 using 'https://github.com/Gkiokan/ps4-remote-pkg-sender' (Server starts and shows successful connection to PS4 RPI on port 12801).

Logs - 
[2022-05-09 20:49:24] Staring web server:
[SERVER] IP: 192.168.1.XXX Port: 11715
[CONSOLE] IP: 192.168.1.XXX Port: 12801

Details -
MacBook Air M1.
Firewall Temporarily Disabled.
PS4 and Mac are on the same subnet.
Server Port: 11715
RPI Port: 12801

**Comment by TechUnRestricted** [comment]
Hello, @Flute7!
Thank you for your report. It seems like I forgot to add something before publishing.
Can you try a new version?
Thank you.

https://github.com/TechUnRestricted/PSDirectSender/releases/download/1.0/Release.1.0b.dmg

**Comment by Flute7** [comment]
Hi, @TechUnRestricted.

Thanks for the update. All is working perfectly with version 1.0b. Successfully started server and sent packages to PS4 without a hitch.

Great program, very clean! Thank you.
